apiVersion: v1
kind: Service
metadata:
  name: apartment-price-api-svc
spec:
  type: NodePort
  selector:
    app: apartment-price-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
